import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className="bg-[#050505] text-white">
        {/* TOP MENU 100% WIDTH */}
        <nav className="fixed top-0 left-0 w-full h-14 border-b border-white/10 bg-black/50 backdrop-blur-md z-[100] flex items-center px-8 justify-between">
          <div className="flex items-center gap-8">
            <Link
              href="/"
              className="text-blue-400 font-bold tracking-tighter hover:opacity-80 transition-opacity"
            >
              WOLFCODE<span className="text-white/50 font-light">_CMS</span>
            </Link>

            <div className="flex gap-6 text-xs uppercase tracking-widest font-medium">
              <Link href="/" className="hover:text-blue-400 transition-colornpm s border-b border-blue-500 pb-1">
                Unity Event Manager
              </Link>
              <Link href="dialogue-manager" className="text-slate-500 hover:text-white transition-colors pb-1">
                Dialogue Event Manager
              </Link>
            </div>
          </div>

          <div className="text-[10px] text-slate-500 font-mono italic">
            v1.0.2 - Connected to Unity
          </div>
        </nav>

        {/* Contenido de la página con padding-top para no quedar debajo del menú */}
        <div className="pt-14">
          {children}
        </div>
      </body>
    </html>
  );
}
