// ARCHIVO GENERADO AUTOMÁTICAMENTE - NO EDITAR MANUALMENTE
// Fuente: ActionType.enum.cs

export enum ActionType {
    ANIMATE_OBJECT = "ANIMATE_OBJECT",
    SHOW_DIALOG = "SHOW_DIALOG",
    REMOVE_COLLISION = "REMOVE_COLLISION",
    DESTROY_ENTITY = "DESTROY_ENTITY",
    SLEEP = "SLEEP",
    CHANGE_SCENE = "CHANGE_SCENE",
    CHANGE_GAME_STATE = "CHANGE_GAME_STATE",
    SPAWN_OBJECT = "SPAWN_OBJECT",
    SET_POSITION_PLAYER = "SET_POSITION_PLAYER",
    FADE_IN = "FADE_IN",
    FADE_OUT = "FADE_OUT"
}

export const ACTIONTYPE_TYPES = Object.values(ActionType) as ActionType[];
